from __future__ import annotations

from pathlib import Path

import pytest


HEADER = [
    "source",
    "target",
    "source_genesymbol",
    "target_genesymbol",
    "is_directed",
    "is_stimulation",
    "is_inhibition",
    "consensus_direction",
    "consensus_stimulation",
    "consensus_inhibition",
    "sources",
    "references",
    "omnipath",
    "kinaseextra",
    "ligrecextra",
    "pathwayextra",
    "mirnatarget",
    "dorothea",
    "collectri",
    "tf_target",
    "lncrna_mrna",
    "tf_mirna",
    "small_molecule",
    "dorothea_curated",
    "dorothea_chipseq",
    "dorothea_tfbs",
    "dorothea_coexp",
    "dorothea_level",
    "type",
    "curation_effort",
    "extra_attrs",
    "evidences",
    "ncbi_tax_id_source",
    "entity_type_source",
    "ncbi_tax_id_target",
    "entity_type_target",
]

ROWS = [
    [
        "P1",
        "P2",
        "GENE1",
        "GENE2",
        "True",
        "True",
        "False",
        "True",
        "True",
        "False",
        "omnipath",
        "PMID:1",
        "True",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "",
        "post_translational",
        "1",
        "",
        "",
        "9606",
        "protein",
        "9606",
        "protein",
    ],
    [
        "P2",
        "P3",
        "GENE2",
        "GENE3",
        "True",
        "False",
        "True",
        "True",
        "False",
        "True",
        "omnipath",
        "PMID:2",
        "True",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "False",
        "",
        "post_translational",
        "2",
        "",
        "",
        "9606",
        "protein",
        "9606",
        "protein",
    ],
]


@pytest.fixture
def sample_networks_tsv(tmp_path: Path) -> Path:
    path = tmp_path / "sample_networks.tsv"
    lines = ["\t".join(HEADER)]
    lines.extend("\t".join(row) for row in ROWS)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
